build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Squeezelite Player"
  org.opencontainers.image.description: "Turn your Home Assistant into a Squeezelite media player"
  org.opencontainers.image.source: "https://github.com/freundTech/hassio-addon-squeezelite"
  org.opencontainers.image.licenses: "GPL-3.0-or-later"
  org.opencontainers.authors: "Adrian Freund"
